name: "Build & deploy"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Sphinx build
    runs-on: windows-latest
    steps:
      - name: Checkout repository ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Cache pip ğŸ´
        uses: actions/cache@v3
        with:
          path: ~/appdata/local/pip/cache
          key: ${{ runner.os }}-pip-${{ hashFiles('environment.yml') }}
          restore-keys: ${{ runner.os }}-pip
      - name: Setup micromamba ğŸ
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          cache-downloads: true
          cache-downloads-key: ${{ runner.os }}-microconda
          # cache-env: true
          # cache-env-key: ${{ runner.os }}-microconda-${{ hashFiles('environment.yml') }}
      - name: Sphinx build ğŸ“–
        shell: pwsh
        run: |
          micromamba activate doc
          sphinx-build -M html doc publish -j auto
      - name: Upload artifacts ğŸ“¦ğŸ”º
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: publish/html
  deploy:
    name: GitHub Pages deploy
    concurrency: ci-${{ github.ref }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Download artifacts ğŸ“¦ğŸ”»
        uses: actions/download-artifact@v3
        with:
          name: publish
          path: publish
      - name: Deploy to GitHub Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: publish

