name: "build & deploy"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Sphinx build
    runs-on: windows-latest
    steps:
      - name: Checkout repository ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Cache miniconda ğŸ²
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os}}-miniconda-${{ hashFiles('environment.yml') }}
          restore-keys: ${{ runner.os}}-miniconda
      - name: Cache pip ğŸ´
        uses: actions/cache@v2
        with:
          path: ~/appdata/local/pip/cache
          key: ${{ runner.os}}-pip-${{ hashFiles('environment.yml') }}
          restore-keys: ${{ runner.os}}-pip
      - name: Setup miniconda ğŸ³
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          auto-activate-base: false
          channels: conda-forge
          channel-priority: strict
          show-channel-urls: true
          environment-file: environment.yml
          activate-environment: doc
          use-only-tar-bz2: true
      - name: Collect info ğŸ“‹
        shell: pwsh
        run: |
          conda info
          conda list
          python -m pip cache dir
      - name: Sphinx build ğŸ“–
        shell: pwsh
        run: |
          sphinx-build -M html doc publish -j auto
      - name: Upload artifacts ğŸ“¦ğŸ”º
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: publish/html

  deploy:
    name: GitHub Pages deploy
    concurrency: ci-${{ github.ref }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Download artifacts ğŸ“¦ğŸ”»
        uses: actions/download-artifact@v3
        with:
          name: publish
          path: publish
      - name: Deploy to GitHub Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: publish

